#服务器基本信息
Server:
  Port: "8080" #服务器端口
  Address: "localhost" #服务器地址

#数据库
DataBase:
  User: "root"
  Password: "123456"
  Name: "Black"
  Port: "3306"
  Charset: "utf8mb4"
  ParseTime: "True"
  Loc: "Local"
  Limit: 15

#redis
Redis:
  Addr: "localhost:6379"
  Password: ""
  DB:        0
  PoolSize:  20

#日志
Log:
  MaxSize:    1
  MaxBackups: 5
  MaxAge:     30
  Compress:   false


